"""init_db

Revision ID: b1291a816f0c
Revises: fcbba4568e2d
Create Date: 2023-10-13 09:28:50.445621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1291a816f0c'
down_revision = 'fcbba4568e2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
